### ISSUE TITLE
[CHORE] Add Template of Opening Feature Request and Bug Issues

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Apps.Notion#1]
# Task :rocket:
- [x] Intialise RC App
- [x] Notion Icon
- [x] add bug form
- [x] add feat form
- [x] add pr template
